export const SERVER_MESSAGE_OPPONENT_MESSAGE = "serverMessageOpponentMessage";
export const SERVER_GAME_UPDATE_GAME_STARTED = "serverGameUpdateGameStarted";
export const SERVER_GAME_UPDATE_GAME_CHANGED = "serverGameUpdateGameChanged";
export const SERVER_GAME_OPPONENT_RECEIVED_GAME_STATUS_CHANGE_CONFIRMATION = "serverGameOpponentReceivedGameStatusChangeConfirmation";
export const SERVER_GAME_UPDATE_GAME_ENDED = "serverGameUpdateGameEnded";
export const SERVER_SESSION_STATUS_UPDATE_HEARTBEAT = "serverSessionStatusUpdateHeartbeat";
export const SERVER_SESSION_STATUS_UPDATE_PAIRED_SESSION_DISCONNECTED = "serverSessionStatusUpdatePairedSessionDisconnected";
export const SERVER_SESSION_STATUS_UPDATE_SESSION_REJECTED = "serverSessionStatusUpdateSessionRejected";
