export const FIRST_PLAYER_ORDER = "1st player"
export const SECOND_PLAYER_ORDER = "2nd player"
export const FIRST_PLAYER_SQUARE_VALUE = "X"
export const SECOND_PLAYER_SQUARE_VALUE = "O"
export const MESSAGE_RECEIVED_CHECKING_INTERVAL = 1000;
export const MESSAGE_RECEIVED_CHECKING_TOTAL_TIME = 30000;
